src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>UID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>UID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>UID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>UID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Event_Application__c.object
<CustomObject>
    <fields>
        <fullName>Applicant__c</fullName>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Event Applications</relationshipLabel>
        <relationshipName>Event_Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Event Applications</relationshipLabel>
        <relationshipName>Event_Applications</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>UID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>UID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Event Application</label>
    <nameField>
        <displayFormat>EVT-APP-{0000}</displayFormat>
        <label>Event Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/EventApplicationControllerREST.cls
@RestResource(urlMapping='/EventApplication')
global with sharing class EventApplicationControllerREST {

    @HttpPost
    global static String doEventApplicationPost(final List<EventApplication> eventApplications) {

        List<Event_Application__c> eventApps = buildEventApplicationsFromRequest(eventApplications);
        List<Database.SaveResult> saveResults = Database.insert(eventApps, false);
        return buildResponse(saveResults, eventApps);
    }

    private static String buildResponse(final List<Database.SaveResult> saveResults, final List<Event_Application__c> eventApps) {

        List<EventApplicationResponse> response = new List<EventApplicationResponse>();

        for (Integer i = 0; i < saveResults.size(); i++) {
            response.add(buildRecordResponse(saveResults[i], eventApps[i]));
        }

        return JSON.serialize(response);
    }

    private static EventApplicationResponse buildRecordResponse(final Database.SaveResult sr, Event_Application__c evtApp) {
        String errorMessage = sr.isSuccess() ? null : sr.getErrors()[0].getMessage();
        return new EventApplicationResponse(evtApp.Event__r.UID__c, evtApp.Applicant__r.UID__c, sr.isSuccess(), errorMessage);
    }

    private static List<Event_Application__c> buildEventApplicationsFromRequest(final List<EventApplication> eventApplications) {

        List<Event_Application__c> eventApps = new List<Event_Application__c>();

        for (EventApplication evtApp : eventApplications) {
            for (String eventUID : evtApp.events) {
                for (String applicantUID : evtApp.applicants) {

                    eventApps.add(new Event_Application__c(
                       Event__r = new Event__c(UID__c = eventUID),
                       Applicant__r = new Contact(UID__c = applicantUID)
                    ));
                }
            }
        }

        return eventApps;
    }

    global class EventApplication {
        global List<String> events {get;set;}
        global List<String> applicants {get;set;}
    }

    global class EventApplicationResponse {
        global String eventUID {get;set;}
        global String applicantUID {get;set;}
        global Boolean isSubmitted {get;set;}
        global String errorMessage {get;set;}

        global EventApplicationResponse(final String eventUID, final String applicantUId, final Boolean isSubmitted, final String errorMessage) {
            this.eventUID = eventUID;
            this.applicantUID = applicantUID;
            this.isSubmitted = isSubmitted;
            this.errorMessage = errorMessage;
        }
    }

}