src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>UID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>UID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not started</fullName>
                </value>
                <value>
                    <fullName>Live</fullName>
                </value>
                <value>
                    <fullName>Competed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>UID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Event_Application__c.object
<CustomObject>
    <fields>
        <fullName>Applicant__c</fullName>
        <label>Applicant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Event Applications</relationshipLabel>
        <relationshipName>Event_Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Event Applications</relationshipLabel>
        <relationshipName>Event_Applications</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>UID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>UID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Event Application</label>
    <nameField>
        <displayFormat>EVT-APP-{0000}</displayFormat>
        <label>Event Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/EventApplicationControllerRESTTest.cls
@IsTest
private class EventApplicationControllerRESTTest {

    @testSetup
    static void initTestData() {

        insert new List<Contact>{
            new Contact(FirstName = 'Bruce', LastName = 'Wayne', Email = 'brucewayne@mail.com', UID__c = '1111'),
            new Contact(FirstName = 'Peter', LastName = 'Parker', Email = 'peterparker@mail.com', UID__c = '2222')
        };

        insert new List<Event__c> {
            new Event__c(Name = 'Some Fancy event', Status__c = 'Not Started', Start_Date__c = Datetime.now().addDays(1), End_Date__c = Datetime.now().addDays(2), UID__c = '1234'),
            new Event__c(Name = 'Some Virtual event', Status__c = 'Not Started', Start_Date__c = Datetime.now().addDays(1), End_Date__c = Datetime.now().addDays(2), UID__c = '5678')
        };
    }

    @IsTest
    static void testDoEventApplicationPost() {

        final List<Contact> contacts = [SELECT Id, UID__c FROM Contact ORDER BY UID__c ASC];
        System.assertEquals(2, contacts.size());

        final List<Event__c> events = [SELECT Id, UID__c FROM Event__c ORDER BY UID__c ASC];
        System.assertEquals(2, events.size());

        EventApplicationControllerREST.EventApplication evtAppPayload = new EventApplicationControllerREST.EventApplication();
        evtAppPayload.events = new List<String> {'1234'};
        evtAppPayload.applicants = new List<String> {'1111'};

        Test.startTest();
        String response = EventApplicationControllerREST.doEventApplicationPost(new List<EventApplicationControllerREST.EventApplication>{evtAppPayload});

        List<EventApplicationControllerREST.EventApplicationResponse> evtAppResponse = (List<EventApplicationControllerREST.EventApplicationResponse>)JSON.deserialize(response, List<EventApplicationControllerREST.EventApplicationResponse>.class);
        System.assertEquals(1, evtAppResponse.size());
        System.assert(evtAppResponse[0].isSubmitted);
        System.assertEquals(null, evtAppResponse[0].errorMessage);
        System.assertEquals(contacts[0].UID__c, evtAppResponse[0].applicantUID);
        System.assertEquals(events[0].UID__c, evtAppResponse[0].eventUID);

        List<Event_Application__c> evtApplications = [SELECT Id, Event__c, Applicant__c FROM Event_Application__c];
        System.assertEquals(1, evtApplications.size());
        System.assertEquals(contacts[0].Id, evtApplications[0].Applicant__c);
        System.assertEquals(events[0].Id, evtApplications[0].Event__c);

        evtAppPayload.events = new List<String> {'1234', '5678'};
        evtAppPayload.applicants = new List<String> {'1111', '2222'};

        response = EventApplicationControllerREST.doEventApplicationPost(new List<EventApplicationControllerREST.EventApplication>{evtAppPayload});
        Test.stopTest();

        evtAppResponse = (List<EventApplicationControllerREST.EventApplicationResponse>)JSON.deserialize(response, List<EventApplicationControllerREST.EventApplicationResponse>.class);
        System.assertEquals(4, evtAppResponse.size());
        System.assert(!evtAppResponse[0].isSubmitted);
        System.assert(String.isNotBlank(evtAppResponse[0].errorMessage));
        System.assertEquals(contacts[0].UID__c, evtAppResponse[0].applicantUID);
        System.assertEquals(events[0].UID__c, evtAppResponse[0].eventUID);

        Map<String, Integer> applicationsByEvent = new Map<String, Integer>();
        Map<String, Integer> applicationsByUsers = new Map<String, Integer>();

        evtApplications = [SELECT Id, Event__c, Applicant__c FROM Event_Application__c];
        System.assertEquals(4, evtApplications.size());

        for (Event_Application__c evtApp : evtApplications) {

            if (!applicationsByEvent.containsKey(evtApp.Event__c)) {
                applicationsByEvent.put(evtApp.Event__c, 0);
            }

            if (!applicationsByUsers.containsKey(evtApp.Applicant__c)) {
                applicationsByUsers.put(evtApp.Applicant__c, 0);
            }

            Integer count = applicationsByEvent.get(evtApp.Event__c);
            applicationsByEvent.put(evtApp.Event__c, ++count);

            count = applicationsByUsers.get(evtApp.Applicant__c);
            applicationsByUsers.put(evtApp.Applicant__c, ++count);
        }

        for (Contact cont : contacts) {
            System.assertEquals(2, applicationsByUsers.get(cont.Id));
        }

        for (Event__c evt : events) {
            System.assertEquals(2, applicationsByEvent.get(evt.Id));
        }
    }
}