src/objects/Event_Limitation__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Current_Event_Count__c</fullName>
        <label>Current Event Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Events_Limit__c</fullName>
        <label>Events Limit</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Event Limitation</label>
</CustomObject>

src/classes/EventLimitationService.cls
public with sharing class EventLimitationService {

    public static Event_Limitation__c ORG_DEFAULT_LIMITATION_LIMITATION = Event_Limitation__c.getOrgDefaults();

    public static Event_Limitation__c userSettings {
        get {
            userSettings = Event_Limitation__c.getInstance();
            if (null == userSettings.Id) {
                userSettings.Events_Limit__c = ORG_DEFAULT_LIMITATION_LIMITATION.Events_Limit__c;
                userSettings.Current_Event_Count__c = 0;
                userSettings.Month__c = Date.today().month();
                insert userSettings;
            }

            if (Date.today().month() != userSettings.Month__c) {
                userSettings.Month__c = Date.today().month();
                userSettings.Current_Event_Count__c = 0;
                update userSettings;
            }

            return userSettings;
        }
        set;
    }

    public class EventLimitationException extends Exception {}
}